"""
Platform and product brand registry for Glider Buddy System.

Canonical machine IDs stay snake_case (wave_glider, slocum). URL prefixes are
kebab-case. Import helpers from here rather than scattering string literals.
"""

from .registry import (
    AREA_TEAM,
    PLATFORM_PLACEHOLDER_LOGO,
    PLATFORM_SLOCUM,
    PLATFORM_WAVE_GLIDER,
    PLATFORMS,
    PRODUCT_FAVICON_PATH,
    PRODUCT_FAVICON_SVG_PATH,
    PRODUCT_LOGO_PATH,
    PRODUCT_NAME_FULL,
    PRODUCT_NAME_SHORT,
    TEAM_DISPLAY_NAME,
    TEAM_HOME_URL,
    TEAM_URL_PREFIX,
    PlatformSpec,
    buddy_title_for,
    display_name_for,
    get_platform,
    home_url_for,
    html_path_for,
    is_known_platform,
    is_team_path,
    known_platform_ids,
    platform_labels_map,
    platform_page_context,
    resolve_platform_from_path,
    team_buddy_title,
    url_prefix_for,
)

__all__ = [
    "AREA_TEAM",
    "PLATFORM_PLACEHOLDER_LOGO",
    "PLATFORM_SLOCUM",
    "PLATFORM_WAVE_GLIDER",
    "PLATFORMS",
    "PRODUCT_FAVICON_PATH",
    "PRODUCT_FAVICON_SVG_PATH",
    "PRODUCT_LOGO_PATH",
    "PRODUCT_NAME_FULL",
    "PRODUCT_NAME_SHORT",
    "TEAM_DISPLAY_NAME",
    "TEAM_HOME_URL",
    "TEAM_URL_PREFIX",
    "PlatformSpec",
    "buddy_title_for",
    "display_name_for",
    "get_platform",
    "home_url_for",
    "html_path_for",
    "is_known_platform",
    "is_team_path",
    "known_platform_ids",
    "platform_labels_map",
    "platform_page_context",
    "resolve_platform_from_path",
    "team_buddy_title",
    "url_prefix_for",
]
